Watching for file changes with StatReloader
"GET / HTTP/1.1" 200 247
Not Found: /favicon.ico
"GET /favicon.ico HTTP/1.1" 404 2444
F:\Python\django\HomeWorkSite\HomeWorkapp1\views.py changed, reloading.
Watching for file changes with StatReloader
"GET / HTTP/1.1" 200 246
F:\Python\django\HomeWorkSite\HomeWorkapp1\views.py changed, reloading.
Watching for file changes with StatReloader
"GET / HTTP/1.1" 200 247
"GET /about/ HTTP/1.1" 200 285
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Watching for file changes with StatReloader
"GET / HTTP/1.1" 200 247
Not Found: /favicon.ico
"GET /favicon.ico HTTP/1.1" 404 2444
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Watching for file changes with StatReloader
"GET / HTTP/1.1" 200 247
Watching for file changes with StatReloader
Watching for file changes with StatReloader
"GET / HTTP/1.1" 200 1114
Not Found: /favicon.ico
"GET /favicon.ico HTTP/1.1" 404 2853
"GET /user/1 HTTP/1.1" 301 0
Internal Server Error: /user/1/
Traceback (most recent call last):
  File "F:\Python\django\HomeWorkSite\djangovenv\Lib\site-packages\django\db\backends\utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\Python\django\HomeWorkSite\djangovenv\Lib\site-packages\django\db\backends\sqlite3\base.py", line 328, in execute
    return super().execute(query, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
sqlite3.OperationalError: no such table: HomeWorkapp3_user

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "F:\Python\django\HomeWorkSite\djangovenv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "F:\Python\django\HomeWorkSite\djangovenv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\Python\django\HomeWorkSite\HomeWorkapp3\views.py", line 15, in basket
    user = User.objects.filter(pk=user_id).first()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\Python\django\HomeWorkSite\djangovenv\Lib\site-packages\django\db\models\query.py", line 1057, in first
    for obj in queryset[:1]:
  File "F:\Python\django\HomeWorkSite\djangovenv\Lib\site-packages\django\db\models\query.py", line 398, in __iter__
    self._fetch_all()
  File "F:\Python\django\HomeWorkSite\djangovenv\Lib\site-packages\django\db\models\query.py", line 1881, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\Python\django\HomeWorkSite\djangovenv\Lib\site-packages\django\db\models\query.py", line 91, in __iter__
    results = compiler.execute_sql(
              ^^^^^^^^^^^^^^^^^^^^^
  File "F:\Python\django\HomeWorkSite\djangovenv\Lib\site-packages\django\db\models\sql\compiler.py", line 1562, in execute_sql
    cursor.execute(sql, params)
  File "F:\Python\django\HomeWorkSite\djangovenv\Lib\site-packages\django\db\backends\utils.py", line 102, in execute
    return super().execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\Python\django\HomeWorkSite\djangovenv\Lib\site-packages\django\db\backends\utils.py", line 67, in execute
    return self._execute_with_wrappers(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\Python\django\HomeWorkSite\djangovenv\Lib\site-packages\django\db\backends\utils.py", line 80, in _execute_with_wrappers
    return executor(sql, params, many, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\Python\django\HomeWorkSite\djangovenv\Lib\site-packages\django\db\backends\utils.py", line 84, in _execute
    with self.db.wrap_database_errors:
  File "F:\Python\django\HomeWorkSite\djangovenv\Lib\site-packages\django\db\utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "F:\Python\django\HomeWorkSite\djangovenv\Lib\site-packages\django\db\backends\utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\Python\django\HomeWorkSite\djangovenv\Lib\site-packages\django\db\backends\sqlite3\base.py", line 328, in execute
    return super().execute(query, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
django.db.utils.OperationalError: no such table: HomeWorkapp3_user
"GET /user/1/ HTTP/1.1" 500 137208
Watching for file changes with StatReloader
"GET / HTTP/1.1" 200 1114
"GET /user/1/ HTTP/1.1" 200 194
"GET /user/2/ HTTP/1.1" 200 194
"GET /user/2/ HTTP/1.1" 200 223
Watching for file changes with StatReloader
"GET / HTTP/1.1" 200 1114
"GET /user/1/ HTTP/1.1" 200 223
"GET /user/2 HTTP/1.1" 301 0
"GET /user/2/ HTTP/1.1" 200 651
"GET /user/5 HTTP/1.1" 301 0
"GET /user/5/ HTTP/1.1" 200 651
"GET /user/5/ HTTP/1.1" 200 658
"GET /user_sorted/5/1 HTTP/1.1" 301 0
"GET /user_sorted/5/1/ HTTP/1.1" 200 567
"GET /user_sorted/8/12/ HTTP/1.1" 200 271
"GET /user_sorted/8/1/ HTTP/1.1" 200 270
"GET /user_sorted/9/1/ HTTP/1.1" 200 270
"GET /user_sorted/10/1/ HTTP/1.1" 200 270
"GET /user_sorted/3/1/ HTTP/1.1" 200 766
Watching for file changes with StatReloader
"GET /user_sorted/10/1/ HTTP/1.1" 200 270
"GET /user_sorted/11/1/ HTTP/1.1" 200 271
"GET /user_sorted/12/1/ HTTP/1.1" 200 270
"GET /user_sorted/38/1/ HTTP/1.1" 200 265
"GET /user_sorted/1/1/ HTTP/1.1" 200 265
"GET /user_sorted/3/1/ HTTP/1.1" 200 766
"GET /user_sorted/3/12/ HTTP/1.1" 200 767
"GET /user_sorted/4/12/ HTTP/1.1" 200 271
"GET /user_sorted/8/12/ HTTP/1.1" 200 271
Watching for file changes with StatReloader
"GET / HTTP/1.1" 200 637
Not Found: /favicon.ico
"GET /favicon.ico HTTP/1.1" 404 2853
Not Found: /HomeWorkapp3/product_update_id
"GET /HomeWorkapp3/product_update_id HTTP/1.1" 404 2910
F:\Python\django\HomeWorkSite\HomeWorkapp3\urls.py changed, reloading.
Watching for file changes with StatReloader
F:\Python\django\HomeWorkSite\HomeWorkapp3\urls.py changed, reloading.
Watching for file changes with StatReloader
"GET / HTTP/1.1" 200 637
Not Found: /HomeWorkapp3/product_update_id
"GET /HomeWorkapp3/product_update_id HTTP/1.1" 404 3308
Watching for file changes with StatReloader
"GET / HTTP/1.1" 200 637
Not Found: /HomeWorkapp3/product_update_id
"GET /HomeWorkapp3/product_update_id HTTP/1.1" 404 3308
"GET / HTTP/1.1" 200 1586
Not Found: /homework4/product_update_id
"GET /homework4/product_update_id HTTP/1.1" 404 3299
"GET / HTTP/1.1" 200 1585
Not Found: /HomeWorkapp3/product_update_id
"GET /HomeWorkapp3/product_update_id HTTP/1.1" 404 3308
"GET / HTTP/1.1" 200 1572
"GET /product_update_id HTTP/1.1" 301 0
"GET /product_update_id/ HTTP/1.1" 200 1288
"POST /product_update_id/ HTTP/1.1" 302 0
Not Found: /HomeWorkapp3/product_update/6
"GET /HomeWorkapp3/product_update/6 HTTP/1.1" 404 3305
F:\Python\django\HomeWorkSite\HomeWorkapp3\views.py changed, reloading.
Watching for file changes with StatReloader
"GET /product_update_id/ HTTP/1.1" 200 1288
"POST /product_update_id/ HTTP/1.1" 302 0
"GET /product_update/4 HTTP/1.1" 200 1304
"GET /product_update_id/ HTTP/1.1" 200 1288
